#!/usr/bin/env python3
"""Manual hardware smoke report scaffolding."""

from __future__ import annotations

import datetime as _dt
import os
import platform
from pathlib import Path

import brand
import storage
import ui


def _default_report_path() -> Path:
    return Path(storage.path("manual-smoke")) / "MANUAL_SMOKE_REPORT.md"


def _fence(text: str, lang: str = "text") -> str:
    return f"~~~{lang}\n{text.strip()}\n~~~"


def validation_errors(path: Path) -> list[str]:
    if not path.exists():
        return [f"evidence report not found: {path}"]

    text = path.read_text(encoding="utf-8")
    required = [
        "## Results",
        "| Version prints expected release |",
        "| Selftest passes |",
        "| Doctor reports environment |",
        "| `test E` captures the key label |",
        "| Watch background starts |",
        "| No typed private text is stored |",
    ]
    errors = [f"missing required section: {item}" for item in required if item not in text]

    rows = [
        [cell.strip() for cell in line.strip().strip("|").split("|")]
        for line in text.splitlines()
        if line.strip().startswith("|")
    ]
    if any(len(row) >= 3 and not row[1] and not row[2] for row in rows):
        errors.append("results table still has blank Pass/Fail and Evidence cells")

    if "Keyboard brand/model:\n- Keyboard type:" in text or "Keyboard brand/model:\r\n- Keyboard type:" in text:
        errors.append("keyboard brand/model is blank")

    if "local checkout / GitHub install / executable artifact" in text:
        errors.append("install-source placeholder is still present")

    if "hardware-smoke-pass" not in text:
        errors.append("release claim does not record hardware-smoke-pass")

    return errors


def check_report(path: Path) -> int:
    errors = validation_errors(path)
    ui.banner("manual smoke check")
    if errors:
        print("  " + ui.c("not ready for hardware-smoke-pass", "BAD", "BLD"))
        for error in errors:
            print("  " + ui.c("- " + error, "WRN"))
        print("  " + ui.c("This does not change docs/MANUAL_SMOKE_RESULT.md.", "DIM"))
        return 1
    print("  " + ui.c("evidence report is filled enough for hardware-smoke-pass.", "OK", "BLD"))
    print("  " + ui.c("This only validates the report; it does not record the gate result.", "DIM"))
    print("  " + ui.c("Record with scripts/record-manual-smoke-result.ps1 after review.", "DIM"))
    return 0


def build_report() -> str:
    now = _dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %z")
    runtime_dir = storage.data_dir()
    version = brand.VERSION
    windows = f"{platform.system()} {platform.release()} ({platform.version()})"
    python = platform.python_version()
    commands = "\n".join([
        "keysurgeon --version",
        "keysurgeon selftest",
        "keysurgeon --plain doctor",
        "keysurgeon test E",
        "keysurgeon watch --bg",
        "keysurgeon watch --status",
        "keysurgeon watch --stop",
        "keysurgeon watch --status",
        "keysurgeon export --out keysurgeon-export-after-smoke.md",
        "keysurgeon proof --json",
    ])
    return f"""# Manual Smoke Report

Generated by `keysurgeon smoke` on {now}.

This report is a safe scaffold for a real Windows keyboard smoke run.
This scaffold does not prove hardware behavior until the interactive commands
below are run on a real keyboard and the results table is filled in.

## Environment

- Date: {now}
- KeySurgeon version: {version}
- Windows version: {windows}
- Python version: {python}
- Runtime data dir: `{runtime_dir}`
- Install source: local checkout / GitHub install / executable artifact
- Keyboard brand/model:
- Keyboard type: hot-swap / soldered mechanical / membrane / laptop / unknown

## Commands To Run

Close applications where accidental typing matters, then run:

{_fence(commands, "powershell")}

## Results

| Check | Pass/Fail | Evidence |
|---|---|---|
| Version prints expected release |  |  |
| Selftest passes |  |  |
| Doctor reports environment |  |  |
| `test E` captures the key label |  |  |
| `test E` exits with a readable verdict |  |  |
| Watch background starts |  |  |
| Watch status reports state |  |  |
| Watch stop stops the recorded PID |  |  |
| Runtime JSON stays under expected data dir |  |  |
| No typed private text is stored |  |  |

## Chatter Evidence

Only fill this section if a known chattering key or controlled repeat input was
tested.

- Key label:
- Verdict:
- Score:
- Timing evidence:
- Repair ladder shown:

## Release Claim

Choose one:

- `hardware-smoke-pass`: hook path and watcher behavior passed on a real keyboard.
- `hardware-smoke-partial`: some behavior passed, but gaps remain.
- `hardware-smoke-fail`: do not claim real hardware behavior yet.

Notes:
"""


def run(args=None) -> int:
    args = args or []
    out = None
    check = None
    i = 0
    while i < len(args):
        if args[i] == "--out" and i + 1 < len(args):
            out = Path(args[i + 1])
            i += 1
        elif args[i] == "--check" and i + 1 < len(args):
            check = Path(args[i + 1])
            i += 1
        i += 1
    if check:
        return check_report(check)
    path = out or _default_report_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_report(), encoding="utf-8")
    ui.banner("manual smoke")
    print("  " + ui.c("report scaffold written:", "OK", "BLD"))
    print("  " + ui.c(str(path), "DIM"))
    print("  " + ui.c("interactive real-keyboard steps are still required.", "WRN"))
    print("  " + ui.c("do not mark hardware-smoke-pass until the table is filled.", "WRN"))
    return 0
