param(
    [string]$Out = ".runtime\manual-smoke\MANUAL_SMOKE_REPORT.md"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$root = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
$outPath = Join-Path $root $Out

function Capture {
    param([scriptblock]$Command)
    try {
        return ((& $Command 2>&1) -join "`n").Trim()
    }
    catch {
        return $_.Exception.Message
    }
}

Push-Location $root
try {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outPath) | Out-Null

    $version = Capture { python keysurgeon.py --version }
    $doctor = Capture { python keysurgeon.py --plain doctor }
    $selftest = Capture { python keysurgeon.py selftest }
    $export = Capture { python keysurgeon.py export }
    $date = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
    $fence = "~~~"

    $report = @"
# Manual Smoke Report

Generated by `scripts\manual-keyboard-smoke.ps1` on $date.

This helper records safe non-interactive checks and the exact interactive
commands still required. It does not prove real keyboard hook behavior until a
human runs the interactive steps below on a real Windows keyboard.

For installed or executable builds, use `keysurgeon smoke --out MANUAL_SMOKE_REPORT.md`
to create the same kind of safe scaffold without needing this source script.

## Environment

- Date: $date
- Install source: local checkout / GitHub install / executable artifact
- Keyboard brand/model:
- Keyboard type: hot-swap / soldered mechanical / membrane / laptop / unknown

## Non-Interactive Checks

### Version

${fence}text
$version
${fence}

### Doctor

${fence}text
$doctor
${fence}

### Selftest

${fence}text
$selftest
${fence}

### Redacted Export

${fence}text
$export
${fence}

## Interactive Commands To Run

Close applications where accidental typing matters, then run:

${fence}powershell
python keysurgeon.py test E
python keysurgeon.py watch --bg
python keysurgeon.py watch --status
python keysurgeon.py watch --stop
python keysurgeon.py watch --status
python keysurgeon.py export --out .runtime\manual-smoke\keysurgeon-export-after-smoke.md
${fence}

After filling this report, record the release-gate result explicitly:

${fence}powershell
.\scripts\record-manual-smoke-result.ps1 -Result hardware-smoke-pass -EvidenceReport docs\MANUAL_SMOKE_REPORT.md -Tester "name" -Keyboard "brand model" -InstallSource "local checkout"
${fence}

Use `hardware-smoke-partial` or `hardware-smoke-fail` instead of pass if any
required check is missing or failed. The recorder will not mark pass without an
evidence report path.

## Results

| Check | Pass/Fail | Evidence |
|---|---|---|
| Version prints expected release |  |  |
| Selftest passes |  |  |
| Doctor reports environment |  |  |
| `test E` captures the key label |  |  |
| `test E` exits with a readable verdict |  |  |
| Watch background starts |  |  |
| Watch status reports state |  |  |
| Watch stop stops the recorded PID |  |  |
| Runtime JSON stays under expected data dir |  |  |
| No typed private text is stored |  |  |

## Chatter Evidence

Only fill this section if a known chattering key or controlled repeat input was
tested.

- Key label:
- Verdict:
- Score:
- Timing evidence:
- Repair ladder shown:

## Release Claim

Choose one:

- `hardware-smoke-pass`: hook path and watcher behavior passed on a real keyboard.
- `hardware-smoke-partial`: some behavior passed, but gaps remain.
- `hardware-smoke-fail`: do not claim real hardware behavior yet.

Notes:
"@

    $report | Set-Content -LiteralPath $outPath -Encoding utf8
    Write-Host "KEYSURGEON_MANUAL_SMOKE_SCAFFOLD_OK $outPath"
    Write-Host "INTERACTIVE_STEPS_REQUIRED"
}
finally {
    Pop-Location
}
